### ISSUE TITLE
IHDP Dataset query 

### ISSUE THREAD

**Issue by aayushagrawal135** [claudiashi57/dragonnet#11]
Hello @claudiashi57,

Could you tell why there are 50 CSVs as dataset for IHDP? Does it make sense to combine all the CSVs into one big CSV and then make observations on them?

**Comment by claudiashi57** [comment]
Hey Aayush,  these separate csvs are random draws of the same data distribution.  These are used to compute the standard error for the ATE. If combined, we won't be able to do that.

**Comment by aayushagrawal135** [comment]
If I understand correctly, since separate csvs are draws from the same distribution, the combined csv would also belong to the same distribution right? If yes, could you help and elaborate why we won't be able to compute standard error on ATE when csvs are combined?

EDIT: As a clarification, I am referring to "combining" as appending the original csvs one below the other thus creating one big csv.

**Comment by claudiashi57** [comment]
to be clear, the IHDP dataset is a semi-synthetic dataset based on a real dataset. The real dataset has  747 observations. It includes covariates information such as age, gender, social economical status. This paper originally introduced and explained the dataset: https://www.tandfonline.com/doi/abs/10.1198/jcgs.2010.08162

The NPCI package uses these fixed observations and simulates treatments and outcomes, e.g, y = f(x) + epsilon.  each replication of the IHDP dataset essentially has different epsilons. 

There are a few reasons we don't want to pool the datasets.  A practical reason is that we will only have an x file with 747 observations, and a Y file with 747*50 observations.
We could replicate the X files as well,  but then the data points won't be independent.

lastly, the ATE is an average causal effect --- there's one ATE for a population. if we only have one dataset, we won't be able to get a standard error, because we only get one estimate.

**Comment by aayushagrawal135** [comment]
That makes sense! Thank you!
