### ISSUE TITLE
Multiple treatments

### ISSUE THREAD

**Issue by hardianlawi** [claudiashi57/dragonnet#4]
Hi, thank you for your work. It is very interesting. I am currently trying to adopt your work to my problem but my problem has several possible treatments and I am having difficulty in generalizing some of the equations. Could you kindly provide some guidance on this?

**Comment by vveitch** [comment]
Can you give more details? In particular,
1. do you have several treatments, where exactly one of them could be applied to a given unit?
2. Or, do you have several treatments, where any subset could be applied a given unit?

If it's the former: To adapt dragonnet just predict all the treatments and build an outcome model to predict Y given each treatment. See the code here https://github.com/vveitch/causal-text-embeddings-tf2 (that's for text data, but the dragonnet part of the architecture---generalized to hydranet---will work the same). 
I'm not sure offhand how to adapt targeted regularization. My first guess is that you should add 1 regularization term (and associated extra parameter) for each contrast you might consider. E.g., if you have treatments {0,1,2} and you care about E[Y|do(T=1)] - E[Y|do(T=0)] and E[Y|do(T=2)] - E[Y|do(T=0)], then you should add one targeted regularization term for each objective. I haven't tested this though, so I don't know how well it'd work.

If you're in the second situation, ¯\_(ツ)_/¯

**Comment by hardianlawi** [comment]
Thank you for your prompt response.

For each unit, only one treatment is applied, although if the same unit is encountered again, a different treatment could be applied. Also, when the treatment is applied, the probability of taking that particular treatment is known so I am not sure if this approach could still be used.

![image](https://user-images.githubusercontent.com/22806872/77081642-e7069280-6a35-11ea-8b19-b87b510e4d2a.png)

I have considered something similar to what you suggested. Specifically, because I have several treatments, I would use `softmax` instead of `sigmoid` to estimate the propensity g^nn and modifying the formula in the picture with Q_tilde(t_i,  x_i; theta, epsilon) = Q^nn(t_i, x_i; theta) + epsilon_(t_i) * t_i / g^nn(t_i, x_i; theta) where epsilon_(t_i) is the extra parameter for t_i.

I am not sure about the term - (1 - t_i) / (1 - g^nn(x_i;theta) in my problem because in my case 1 - g^nn is the probability not applying that particular treatment instead of probability of not applying any treatment

**Comment by vveitch** [comment]
>when the treatment is applied, the probability of taking that particular treatment is known so I am not sure if this approach could still be used.

If this means that assignment is done at random w/ known probabilities, then you probably don't need the heavy duty machinery in this paper---just predict Q from the known g directly. Or you could look at literature on using the TMLE for randomized control trials.

The key point is that the formula in the picture corresponds to a particular contrast: the difference in outcome between T=1 and T=0. To adapt it, you'll need 2 auxillary outcome heads for each contrast (rather than 1 auxillary outcome head for each treatment level). For example, suppose you want the regularization term for the contrast E[Y | do(T=2)] - E[Y | do(T=0)]. In that case, g(x_i) = P(T=2 | T = 2 or T=1, x_i). In practice, you'll need to compute the conditional probabilities by combining the outputs of the softmax layer (e.g., P(T=2  | T = 2 or T=1) = P(T=2) / P(T = 2 or T=1))

**Comment by hardianlawi** [comment]
I think I understand it now. I will close this issue for now. I will reopen it if I have any other questions.

Thank you again for your great help!

**Comment by lyzltysgithub** [comment]
@hardianlawi hello, did you try to realize the multiple treatment of DragNet? I have the same problem as you

**Comment by hardianlawi** [comment]
@lyzltysgithub I didn't use it in the end as as the author mentioned that it was a bit overkill for my use case
